### ISSUE TITLE
Losing tag corners

### ISSUE THREAD

**Issue by mpaffolter** [CogChameleon/MarkerSfM#2]
Hello

I am reconstructing a scene with 10 tags flat on the floor. Each of them is visible by several shots:
Tag-ID, occurrences in 44 images
`{
    "1": 40,
    "2": 33,
    "4": 31,
    "7": 30,
    "6": 44,
    "9": 33,
    "8": 37,
    "0": 30,
    "5": 34,
    "3": 29
}
`
The reconstructed scene looks good, however I only get 5-6 tags (partially) reconstructed. I've tried different settings in the config.yml file, but cannot get more than 6 tags reconstructed. Is there a way to prevent tag corners removal?

Thanks,
Martin
![image](https://user-images.githubusercontent.com/16540939/74440047-91a2f880-4e6d-11ea-9641-4a321f65cfab.png)

**Comment by CogChameleon** [comment]
Hello Martin,

I found that the localization of the corners during detection for markers like AprilTag was less precise than the feature points, so often corners of the markers will be filtered away during triangulation/resectioning.

You could try loosening some of the thresholds in config.yaml under the headings of "# Params for geometric estimation" and "# Params for bundle adjustment". If these quick tests don't work, then I suggest doing some debugging to find out which step of the pipeline is filtering out the points.

If this still doesn't work, then the code probably needs to be changed so that tag corners are forced into triangulation and not filtered.

**Comment by mpaffolter** [comment]
Thank you for answering. I took measurements from all markers, so I could calculate a transformation to room coordinates. After loosening the thresholds I get 7 out of 10 markers with the following results:

4 cameras:
![image](https://user-images.githubusercontent.com/16540939/74964805-5c218080-5414-11ea-9ecc-015b25ee9374.png)

7 marker center points:
![image](https://user-images.githubusercontent.com/16540939/74964827-63488e80-5414-11ea-9d20-13237b73a758.png)

The error is in meters, the accuracy of camera position ground truth is +/-0.05 m for x,y and +/-0.01 m for z.

I notice that the results from marker-mapper are more accurate for both camera and marker position. However, I suspect that MarkerSfM will play out its strength when the camera network is larger.
